import Head from "next/head";
import styles from "../styles/Home.module.css";
import IndexBaseCard from "../components/cards/cardIndex";
import FeaturedCard from "../components/cards/cardFeatured";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Hello main Page</p>
      </main>
    </>
  );
}
