import Head from "next/head";
import IndexBaseCard from "../components/cards/cardIndex";
import {Stack} from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sherlockation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IndexBaseCard />
      </main>
    </>
  );
}
